name: screenshot

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn start
    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: ./images/*.png
    - name: Upload videos
      uses: actions/upload-artifact@v2
      with:
        name: videos
        path: ./videos/*.mkv